FROM node:18.13.0 as base
# Add package file
COPY package.json ./
COPY package-lock.json ./
#COPY scripts/dev.sh ./scripts/dev.sh
# Install deps
RUN npm install

# Copy source
COPY src ./src
COPY tsconfig.json ./tsconfig.json
COPY swagger-doc.json ./swagger-doc.json

# Build dist
RUN npm run build

# Start production image build
FROM gcr.io/distroless/nodejs:18

# Copy node modules and build directory
COPY --from=base ./node_modules ./node_modules
COPY --from=base /dist /dist
#COPY --from=base .env ./env

# Copy static files
COPY src/public dist/src/public

# Expose port 3000
EXPOSE 3000
CMD ["dist/src/server.js"]